# Generated by Django 4.2.3 on 2023-07-09 21:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=256)),
                ('height', models.CharField(max_length=16)),
                ('body_type', models.CharField(max_length=64)),
                ('sexual_orientation', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('bio', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
