# Generated by Django 4.2.3 on 2023-07-09 21:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('p_a_fulfilled', models.BooleanField()),
                ('p_b_fulfilled', models.BooleanField()),
                ('match_time', models.DateTimeField()),
                ('p_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_a_match', to='users.user')),
                ('p_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_b_match', to='users.user')),
            ],
            options={
                'ordering': ['match_time'],
            },
        ),
    ]
