version: '3'

services:
  db:
    image: postgres:13
    container_name: backend_db_1
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0-alpine
    container_name: backend-redis
    restart: always
    volumes:
      - cache-data:/var/lib/redis/data/
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: dockerfile_backend
    ports:
      - "8000:8000"
      - "1883:1883"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
volumes:
  db-data:
  redis-data:
